


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const SET_ROUTE_SUCCESS = "SET_ROUTE_SUCCESS";

export const RESPONSIVE_MODE_ON = "RESPONSIVE_MODE_ON";
export const RESPONSIVE_MODE_OFF = "RESPONSIVE_MODE_OFF";

export const ADVERT_SAVE_CATEGORY = "CREATE_NEW_ADVERT";
export const ADVERT_SAVE_SUB_CATEGORY = "ADVERT_SAVE_SUB_CATEGORY";
export const ADVERT_CLEAR_SUB_CATEGORY = "ADVERT_CLEAR_SUB_CATEGORY";

export const ADVERT_SAVE_DETAIL = "ADVERT_SAVE_DETAIL";


export const START_SAVE_CATEGORIES_ASTATE = "SAVE_CATEGORIES_ASTATE";
export const SUCCESS_SAVE_CATEGORIES_ASTATE = "SUCCESS_SAVE_CATEGORIES_ASTATE";
export const FAILED_SAVE_CATEGORIES_ASTATE = "FAILED_SAVE_CATEGORIES_ASTATE"; 
export const FINISH_SAVE_CATEGORIES_ASTATE = "FINISH_SAVE_CATEGORIES_ASTATE"
export const SAVE_SELECTED_CATEGORIES = "SAVE_SELECTED_CATEGORIES";

export const START_SAVE_SUBCATEGORIES_ASTATE = "START_SAVE_SUBCATEGORIES_ASTATE";
export const SUCCESS_SAVE_SUBCATEGORIES_ASTATE = "SUCCESS_SAVE_SUBCATEGORIES_ASTATE";
export const FAILED_SAVE_SUBCATEGORIES_ASTATE = "FAILED_SAVE_SUBCATEGORIES_ASTATE";
export const SAVE_SELECTED_SUB_cATEGORIES = "SAVE_SELECTED_CATEGORIES";
export const FINISH_SAVE_SUBCATEGORIES_ASTATE = "FINISH_SAVE_SUBCATEGORIES_ASTATE"


export const PRODUCT_ATTIRBUTE_DEFINITIONS = "PRODUCT_ATTIRBUTE_DEFINITIONS";

export const SAVE_SERVICE_INSTANCE = "SAVE_SERVICE_INSTANCE";


